# Generated by Django 5.1.1 on 2024-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimg',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
